// resources/js/components/FilterRowUnesco.vue
<template>
    <div>
        <select class="form-select form-select-sm" v-model="fields.operator">
            <option value="is">has a UNESCO World Heritage List link</option>
            <option value="isnot">has no UNESCO World Heritage List link</option>
        </select>
    </div>
</template>

<script>
    export default {
        data() {
            return {
            };
        },

        props: ['fields'],

        mounted() {

        }
    }
</script>

// resources/js/components/FilterRowUnesco.svelte
<script>
    export let fields = {
        operator: "is"
    }
</script>

<div>
    <select class="form-select form-select-sm" bind:value={fields.operator}>
        <option value="is">has a UNESCO World Heritage List link</option>
        <option value="isnot">has no UNESCO World Heritage List link</option>
    </select>
</div>
